config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  resources :boards
  resources :players
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: redirect('/login')
  get    '/login',   to: 'session#new'
  post   '/login',   to: 'session#create'
  get '/logout',  to: 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
    has_and_belongs_to_many :players, :join_table => :players_boards
    validates :game_name, presence: true, length: {in: 3..20}
    validates :white_player_id, presence: true
    validates :black_player_id, presence: true
end

app/models/player.rb
class Player < ApplicationRecord
    has_and_belongs_to_many :boards, :join_table => :players_boards
    validates :nickname, presence: true, uniqueness: true,
    length: {in: 3..12}
    has_secure_password
    validates :password, presence: true, length: {minimum: 8}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionHelper
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]
  before_action :require_login, only: [:edit, :update, :destroy, :show, :index, :create, :new]

  # GET /boards or /boards.json
  def index
    @boards = Board.where("black_player_id = ? OR white_player_id = ?", current_player.id, current_player.id)
  end

  # GET /boards/1 or /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards or /boards.json
  def create
    @board = current_player.boards.build(board_params)
    @board.white_player_id = current_player.id

    respond_to do |format|
      if @board.save
        format.html { redirect_to board_url(@board), notice: "Board was successfully created." }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if can_edit_board?
      new_move = params[:board][:new_move]
      
      if new_move.present? && valid_move?(new_move)
        if @board.history_string.blank? && current_player.id == @board.white_player_id
          @board.history_string = new_move
        elsif @board.history_string.blank? && current_player.id != @board.white_player_id
          flash[:alert] = "It's not your turn to make a move."
          redirect_to board_path
          return
        else
          if !@board.history_string.include?('/') && current_player.id == @board.black_player_id
            @board.history_string = "/#{new_move}"
          elsif !@board.history_string.include?('/') && current_player.id != @board.black_player_id
            flash[:alert] = "It's not your turn to make a move."
            redirect_to board_path
            return
          else
            history_moves = @board.history_string.split('/')
            if (current_player.id == @board.white_player_id && history_moves.size.even?) ||
               (current_player.id == @board.black_player_id && history_moves.size.odd?)
  
              @board.history_string += "/#{new_move}"
            else
              flash[:alert] = "It's not your turn to make a move."
              redirect_to board_path
              return
            end
          end
        end  
      else
        flash[:alert] = "Invalid move format."
        redirect_to board_path
        return
      end
      
      respond_to do |format|
        if @board.save
          format.html { redirect_to board_url(@board), notice: "Board was successfully updated." }
          format.json { render :show, status: :ok, location: @board }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @board.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:alert] = "You are not one of the players."
      redirect_to board_path
    end
  end
  
  
  
  
  

  # DELETE /boards/1 or /boards/1.json
  def destroy
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url, notice: "Board was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:history_string, :game_name, :white_player_id, :black_player_id)
    end
  
    def valid_move?(move)
      move.match?(/\A[a-h][1-8][a-h][1-8][qnrb]?\z/i)
    end

    def require_login
      unless logged_in?
        redirect_to login_path
      end
    end
    
    def can_edit_board?
      current_player && (current_player.id == @board.white_player_id || current_player.id == @board.black_player_id )
    end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]


  # GET /players or /players.json
  def index
    @players = Player.all
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to player_url(@player), notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to player_url(@player), notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:nickname, :password, :password_confirmation)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    if params[:session].present? && params[:session][:id].present? && params[:session][:password].present?
      player = Player.find_by(nickname: params[:session][:id])
      if player && player.authenticate(params[:session][:password])
        log_in player
        redirect_to player
      else
        render 'new'
      end
    else
      render 'new'
    end
  end
  

  def destroy
    log_out 
    redirect_to root_url
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def index
    # ale że jest środek nocy a ja czytam o lorem ipsum... xD
    @some_variable = 123
    @players = Player.all
    @boards = Board.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def log_in(player)
        session[:player_id] = player.id
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/session_helper.rb
module SessionHelper
    def log_in(player)
        session[:player_id] = player.id
      end

    def current_player
        @current_player ||= Player.find_by(id: session[:player_id])
      end
    
    def logged_in?
        !current_player.nil?
      end

    def log_out
        session.delete(:player_id)
        @current_player = nil
      end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/boards/_board.html.erb
<div id="<%= dom_id(board) %>" style="text-align: center;">
  <% if board.history_string.blank? %>
    <p>No history available.</p>
  <% else %>
    <table style="border-collapse: collapse; margin: 0 auto;">
      <thead>
        <tr>
          <th style="border: 1px solid white; padding: 8px;">
            <% created_by_player = Player.find_by(id: board.white_player_id) %> 
            <% if created_by_player %>
              <%= created_by_player.nickname %>
            <% else %>
              Unknown Player
            <% end %>
          </th>
          <th style="border: 1px solid white; padding: 8px;">
            <% created_by_player = Player.find_by(id: board.black_player_id) %> 
            <% if created_by_player %>
              <%= created_by_player.nickname %>
            <% else %>
              Unknown Player
            <% end %>
          </th>
        </tr>
      </thead>
      <tbody>
        <% moves = board.history_string.split('/') %>
        <% moves.each_with_index do |move, index| %>
          <% player = index.even? ? board.white_player : board.black_player %>
          <tr>
            <td style="border: 1px solid white; padding: 8px;">
              <% if index.even? %>
                <%= move %>
              <% end %>
            </td>
            <td style="border: 1px solid white; padding: 8px;">
              <% if index.odd? %>
                <%= move %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <p>
    <strong>Game name:</strong>
    <%= board.game_name %>
  </p>

  <%= form_with(model: board) do |form| %>
    <% if board.errors.any? %>
      <div style="color: red;">
        <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>
        <ul>
          <% board.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% else %>
      <% if flash[:alert].present? %>
        <div style="color: red;">
          <%= flash[:alert] %>
        </div>
      <% end %>
    <% end %>

    <div class="actions" style="display: flex; justify-content: center; margin-top: 20px;">
      <strong>New move:</strong>
      <%= form.text_field :new_move, class: "block-input" %>
      <%= form.submit "Add Move", class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/boards/_edit.html.erb
<%= form_with(model: board) do |form| %>
    <% if board.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>
        <ul>
          <% board.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
      <% else %>
      <% if flash[:alert].present? %>
        <div style="color: red">
          <%= flash[:alert] %>
        </div>
      <% end %>
    <% end %>
  
    <div>
        <%= form.label :game_name, style: "display: block" %>
        <%= form.text_field :game_name %>
    </div>

    <div>
        <%= form.label :history_string, style: "display: block" %>
        <%= form.text_area :history_string %>
    </div>
    
    <%= form.submit %>


  <% end %>
  

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
  <% if board.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>
      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <% else %>
    <% if flash[:alert].present? %>
      <div style="color: red">
        <%= flash[:alert] %>
      </div>
    <% end %>
  <% end %>

  <div class="field">
    <%= form.label :black_player_id %>
    <%= form.collection_select :black_player_id, Player.all, :id, :nickname, prompt: true %>
  </div>

  <div>
    <%= form.label :game_name, style: "display: block" %>
    <%= form.text_field :game_name %>
  </div>

  <div class="actions">
    <%= form.label :new_move, style: "display: block" %>
    <%= form.text_field :new_move, style: "display: block" %>
    <%= form.submit "Add Move", class: "btn-secondary" %>
  </div>
<% end %>

app/views/boards/_new.html.erb
<%= form_with(model: board) do |form| %>
    <% if board.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>
        <ul>
          <% board.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
      <% else %>
      <% if flash[:alert].present? %>
        <div style="color: red">
          <%= flash[:alert] %>
        </div>
      <% end %>
    <% end %>
  
    <div class="field">
      <%= form.label :black_player_id, style: "display: block"%>
      <%= form.collection_select :black_player_id, Player.all, :id, :nickname, prompt: true %>
    </div>
  
    <div>
      <%= form.label :game_name, style: "display: block" %>
      <%= form.text_field :game_name %>
    </div>
  
    <div class="actions">
    
      <%= form.submit "Create Board", class: "btn-secondary" %>
    </div>
  <% end %>
  

app/views/boards/edit.html.erb
<h1>Editing board</h1>
<%= render "edit", board: @board %>
<br>
<div>
  <%= link_to "Show this board", @board %> |
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/index.html.erb
<style>
  .table-white {
    color: white;
  }

  .text-center {
    text-align: center;
  }
</style>

<div class="container">
  <div class="row">
    <div class="col-12">
    <h1 class="text-center">Boards</h1>
      <p style="color: green;"><%= notice %></p>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-12">
      <table class="table table-white">
        <thead>
          <tr>
            <th scope="col">Game Name</th>
            <th scope="col">Created</th>
            <th scope="col">Updated</th>
            <th scope="col">Created By</th>
          </tr>
        </thead>
        <tbody>
          <% @boards.each do |board| %>
            <tr>
              <td><%= link_to board.game_name, board %></td>
              <td><%= board.created_at %></td>
              <td><%= board.updated_at %></td>
              <td>
                <% created_by_player = Player.find_by(id: board.white_player_id) %> 
                <% if created_by_player %>
                  <%= created_by_player.nickname %>
                <% else %>
                  Unknown Player
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-12 mt-3">
      <%= link_to "New board", new_board_path, class: "btn btn-success" %>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<div class="main-content">
  <div class="welcome-banner">
    <div class="welcome-text">
      <div class="d-flex justify-content-center flex-column align-items-center">
        <h1>Creat New Board</h1>

        <% if logged_in? %>
          <%= render "new", board: @board %>
          
        <% else %>
          <p>You must be signed in to create a board.</p>
        <% end %>

        <br>

        <div>
        <p>&nbsp;</p>
          <%= link_to "Back to boards", boards_path, class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<div style="text-align: center;">
  <p style="color: green;"><%= notice %></p>

  <%= render @board %>

  <div style="margin-top: 20px;">
    
    <%= link_to "Back to boards", boards_path, class: "btn btn-secondary" %>

    <%= button_to "Destroy this board", @board, method: :delete, class: "btn btn-danger" %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<span class="navbar-text">
<% if logged_in? %>
<div> Welcome <%= current_player.nickname %> </div>
    <%= link_to "Sign out", logout_path, method: :delete, class: "btn btn-danger" %>
<% else %>
    
<% end %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectFinalV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>

<ul>
  <li><%= link_to "Strona główna", root_path %></li>
  <li><%= link_to "Plansze", boards_path %></li>
  <li><%= link_to "Gracze", players_path %></li>
  <% if logged_in? %>
    <li><%= link_to current_player.nickname, current_player %></li>
    <li><%= link_to "Wyloguj", logout_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Zaloguj", login_path %></li>
  <% end %>
</ul>

</html>

app/views/players/_form.html.erb
<style>
  .container {
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }

  .error-messages {
    color: red;
    margin-bottom: 10px;
  }

  .form-field {
    margin-bottom: 15px;
  }

  .form-field label {
    display: block;
    font-weight: bold;
    margin-bottom: 5px;
  }

  .form-field input[type="text"],
  .form-field input[type="password"] {
    width: 100%;
    padding: 8px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }

  .form-actions {
    text-align: center;
  }

  .button {
    display: inline-block;
    padding: 8px 16px;
    background-color: #ccc;
    color: #fff;
    text-decoration: none;
    border-radius: 5px;
    transition: background-color 0.3s;
  }

  .button:hover {
    background-color: #999;
  }
</style>

<div class="container">
  <%= form_with(model: player) do |form| %>
    <% if player.errors.any? %>
      <div class="error-messages">
        <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

        <ul>
          <% player.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-field">
      <%= form.label :nickname %>
      <%= form.text_field :nickname %>
    </div>

    <div class="form-field">
      <%= form.label :password %>
      <%= form.password_field :password, id: :player_password %>
    </div>

    <div class="form-field">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, id: :player_password_confirmation %>
    </div>

    <div class="form-actions">
      <%= form.submit "Create Player", class: "button" %>
      <%= link_to "Back to Players", players_path, class: "button" %>
    </div>
  <% end %>
</div>

app/views/players/_player.html.erb
<style>
  .player-details {
    border: 1px solid #ccc;
    padding: 10px;
    border-radius: 5px;
    margin-bottom: 10px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  .player-details p {
    margin: 0;
    line-height: 1.5;
  }

  .player-details strong {
    font-weight: bold;
    margin-right: 5px;
  }
</style>

<div class="player-details" id="<%= dom_id(player) %>">
  <p>
    <strong>Nickname:</strong>
    <span><%= player.nickname %></span>
    <p>Action:</p>
    <%= link_to "Edit this player", edit_player_path(player), class: "edit-button" %> |
    <%= link_to "Back to players", players_path, class: "back-button", style: "color: white" %>
    <p>&nbsp;</p>
    <%= form_with(model: player, url: player_path(player), method: :delete, data: { confirm: "Are you sure?" }) do |form| %>
      <%= form.submit "Destroy this player", class: "destroy-button" %>
    <% end %>
    <p>&nbsp;</p>
    <p>Press the button to play:</p>
    <%= link_to "Go to boards", boards_path, class: "back-button", style: "color: white" %>
  </p>
</div>

app/views/players/edit.html.erb
<style>
  .edit-title {
    margin-bottom: 20px;
  }

  .actions {
    margin-top: 20px;
  }

  .actions a {
    display: inline-block;
    background-color: #007bff;
    color: white;
    border: none;
    padding: 5px 10px;
    border-radius: 5px;
    text-decoration: none;
    margin-right: 10px;
  }

  .actions a:hover {
    background-color: #0056b3;
  }
</style>

<h1 class="edit-title">Editing player</h1>

<%= render "form", player: @player %>

<div class="actions">
  <%= link_to "Show this player", @player %>
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/index.html.erb
<style>
  .player-details {
    border: 1px solid #ccc;
    padding: 10px;
    border-radius: 5px;
    margin-bottom: 10px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  .player-details p {
    margin: 0;
    line-height: 1.5;
  }

  .player-details strong {
    font-weight: bold;
    margin-right: 5px;
  }

  .notice {
    color: green;
  }

  .players-container {
    margin-top: 20px;
  }

  .players-container p {
    margin-bottom: 5px;
  }

  .players-container a {
    color: #337ab7;
    text-decoration: none;
  }

</style>

<p class="notice"><%= notice %></p>

<h1>Utworzeni Zawodnicy</h1>

<div class="players-container" id="players">
  <% @players.each do |player| %>
    <div class="player-details">
      <strong>Nickname:</strong>
      <span><%= player.nickname %></span>
      <p>
        <%= link_to "Show this player", player %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New player", new_player_path %>

app/views/players/new.html.erb
<style>
  .new-player-title {
    margin-bottom: 20px;
  }

  .actions {
    margin-top: 20px;
  }

  .actions a {
    color: #337ab7;
    text-decoration: none;
    margin-right: 10px;
  }
</style>

<h1 class="new-player-title">Nowy Zawodnik</h1>

<%= render "form", player: @player %>

<div class="actions">
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/show.html.erb
<style>
  .edit-button {
    background-color: #ffc107;
    color: white;
    border: none;
    padding: 5px 10px;
    border-radius: 5px;
    cursor: pointer;
  }

  .edit-button:hover {
    background-color: #e0a800;
  }

  .back-button {
    background-color: #007bff;
    color: white;
    border: none;
    padding: 5px 10px;
    border-radius: 5px;
    cursor: pointer;
  }

  .back-button:hover {
    background-color: #0056b3;
  }

  .destroy-button {
    background-color: #dc3545;
    color: white;
    border: none;
    padding: 5px 10px;
    border-radius: 5px;
    cursor: pointer;
    display: inline-block;
    margin-right: 10px;
  }

  .destroy-button:hover {
    background-color: #c82333;
  }

  .player-actions {
    margin-top: 20px;
  }

  .player-actions a {
    color: #337ab7;
    text-decoration: none;
    margin-right: 10px;
  }

  .player-actions form {
    display: inline;
  }
</style>

<p class="notice"><%= notice %></p>

<%= render @player %>

app/views/session/new.html.erb
<div class="main-content">
  <div class="welcome-banner">
    <div class="welcome-text">
      <h2>Graj w szachy korespondencyjne!</h2>
      <p>Witaj w aplikacji stworzonej przez Macieja Mrowca oraz Maksyma Wilka w ramach projektu dotyczącego aplikacji mobilnych. Ta aplikacja pozwoli ci rozegrać wiele emocjonujących partii szachów korespondencyjnych.</p>
      <p>Zaloguj się, aby rozpocząć rozgrywkę i cieszyć się grą ze znajomymi.</p>
    </div>
  </div1>

  <div class="logo">
    <%= image_tag('Szachy_logo_biale.png', alt: 'Szachy_logo_biale.png', class: 'logo-img') %>
  </div>
  <div class="plansza">
    <%= image_tag('szachy_plansza.png', alt: 'szachy_plansza.png', class: 'plansza-img') %>
    </div>
  </div>

  <div class="login-section">
    <h2 class="login-heading">Sign In</h2>

    <%= form_for(:session, url: login_path) do |f| %>
      <div class="form-group">
      <%= f.label :nickname %>
      <%= f.text_field :id, class: 'form-control' %>    
      </div>

      <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>    
      </div> 

      <div class="spacer"></div>
      
      <div class="actions">
        <%= f.submit "Sign In", class: "btn btn-primary" %>
      <div class="spacer"></div>
      <%= link_to "Registration", new_player_path, class: "btn btn-primary" %>
      </div>
    <% end %>


  </div>
</div>